DO $DO$
BEGIN
  ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS comments TEXT NOT NULL DEFAULT '';
  ALTER TABLE public.quotes ADD COLUMN IF NOT EXISTS show_comments BOOLEAN NOT NULL DEFAULT false;
END $DO$;
